name: Mirror Template Folder

on:
  schedule:
    - cron: '0 0 */3 * *' # Runs every 3 days
  workflow_dispatch: # Allows manual trigger

jobs:
  mirror-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mirror repo with authentication
        run: |
          git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/ahmedfa211/private-backup-of-payload.git .
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Configure sparse checkout and pull only the template
        run: |
          rm -rf templates/with-vercel-website
          git init temp-folder
          cd temp-folder
          git remote add origin https://github.com/payloadcms/payload.git
          git sparse-checkout init --cone
          git sparse-checkout set templates/with-vercel-website
          git pull origin main
          cd ..
          mv temp-folder/templates/with-vercel-website templates/with-vercel-website
          rm -rf temp-folder

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Updated with latest template from payloadcms/payload" || exit 0
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/ahmedfa211/private-backup-of-payload.git HEAD:main
